sudo: required
dist: trusty
language: python

python:
- "3.6"

install:
- add-apt-repository ppa:kivy-team/kivy
- apt-get update
- apt-get install python3-kivy

# Display the Python version we are running now
- python --version

# Install additional requirements (Keras and Tensorflow CPU-Version)
- pip install -r requirements.txt

# List installed packages for debuggin purposes
- pip list

script:
#- pytest --cov=muscima test/
# Run the doc-tests only with Python 3, because in Python 2, it reports strings as u'...' instead of '...' and causes a failure
#- if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pytest --doctest-modules --ignore setup.py; fi

after_success:
- codecov
- coveralls