sudo: required
dist: trusty
language: python

python:
  - "3.6"

install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pytest h5py scikit-image
  - source activate test-environment

  - add-apt-repository ppa:kivy-team/kivy
  - apt-get update
  - apt-get install python3-kivy
  
  # Display the Python version we are running now
  - python --version
  
  # install Pillow for processing images
  - conda install Pillow;
  - conda install -c anaconda lxml
  - conda install -c anaconda libxslt
  - conda install -c anaconda libxml2
  - conda install -c anaconda cython

  # Install additional requirements (Keras and Tensorflow CPU-Version)
  - pip install -r requirements.txt
  
  # List installed packages for debuggin purposes
  - pip list

script:
  #pytest
  - echo "There are no tests here to run yet, so we are done"
  #travis_wait pytest --cov=./ ./

after_success:
  - codecov
  - coveralls