collect_ignore = ["MUSCIMarker/MUSCIMarkerApp.py",
                  "MUSCIMarker/main.py",
                  "MUSCIMarker/annotator_model.py",
                  "MUSCIMarker/cropobject_view.py",
                  "MUSCIMarker/objid_selection.py",
                  "MUSCIMarker/toolkit.py",
                  "MUSCIMarker/mlclass_selection.py",
                  "MUSCIMarker/edge_view.py",
                  "MUSCIMarker/rendering.py",
                  "MUSCIMarker/editor.py",
                  "MUSCIMarker/utils.py",
                  ]
